:production:
  :uri: ldap://localhost:389/
  :base: ou=people,dc=tuenti,dc=com
  :filter: (objectClass=inetOrgPerson)
  :username: cn=admin,dc=tuenti,dc=com
  :password: xpe9su
  :custom_header_key: "X-Tuenti-Custom"
  :custom_header_value: "Powered-by-tuenti-engineering"

:development:
  :uri: ldap://localhost:1389/
  :base: ou=people,dc=tuenti,dc=com
  :filter: (objectClass=inetOrgPerson)
  :username: cn=admin,dc=tuenti,dc=com
  :password: xpe9su
  :custom_header_key: "X-Tuenti-Custom"
  :custom_header_value: "Powered-by-tuenti-engineering"