production:
  uri: ldap://example.com:389/
  base: ou=people,dc=example,dc=com
  filter: (objectClass=inetOrgPerson)
  username: cn=admin,dc=example,dc=com
  password: supersecret

development:
  uri: ldap://localhost:389/
  base: ou=people,dc=example,dc=com
  filter: (objectClass=inetOrgPerson)
  username: cn=admin,dc=example,dc=com
  password: 12345
