:production:
  :uri: ldap://example.com:389/
  :base: ou=people,dc=example,dc=com
  :filter: (objectClass=inetOrgPerson)
  :username: cn=admin,dc=example,dc=com
  :password: supersecret
  :custom_header_key: "X-Example-Custom"
  :custom_header_value: "Powered-by-example-engineering"

:development:
  :uri: ldap://localhost:389/
  :base: ou=people,dc=example,dc=com
  :filter: (objectClass=inetOrgPerson)
  :username: cn=admin,dc=example,dc=com
  :password: 12345
  :custom_header_key: "X-Example-Custom"
  :custom_header_value: "Powered-by-example-engineering"
